version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --save "" --appendonly no

  tor:
    image: dperson/torproxy:latest
    container_name: tor
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    restart: unless-stopped
    depends_on:
      - tor
      - redis

  ranker:
    build: ./ranker
    container_name: ranker
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - SEARXNG_URL=http://searxng:8080
    restart: unless-stopped
    depends_on:
      - searxng
