# SearXNG settings

use_default_settings:
  engines:
    keep_only:
      - google
      - brave
      - startpage
      - wikipedia
      - github
      - arxiv
      - annas archive
      - z-library
      - bt4g

general:
  debug: false
  instance_name: "SearXNG"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: true

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "auto"
  formats:
    - html
    - json

server:
  secret_key: "ultrasecretkey123456789"
  limiter: false
  image_proxy: true
  base_url: false

redis:
  url: redis://redis:6379/0

ui:
  static_use_hash: true
  default_theme: simple
  center_alignment: true
  infinite_scroll: true
  query_in_title: true

outgoing:
  request_timeout: 6.0

engines:
  - name: google
    disabled: false

  - name: brave
    disabled: false

  - name: startpage
    disabled: false

  - name: wikipedia
    disabled: false

  - name: wikipedia (ro)
    engine: wikipedia
    shortcut: wpro
    language: ro
    disabled: false
    
  - name: github
    disabled: false

  - name: arxiv
    disabled: false

  - name: annas archive
    disabled: false
    base_url: https://annas-archive.pm
    timeout: 6.0

  - name: z-library
    disabled: false

  - name: bt4g
    disabled: false
